# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'sber_code' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpenCV2'

end

target 'SberCode_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SberCode_iOS

end